swagger: '2.0'
info:
  title: Fortifi API
  version: '3.142.0'
  termsOfService: 'https://fortifi.io/legal/terms/api'
  description: >
    The second version of the Fortifi API is an exciting step forward towards

    making it easier for businesses to have open access to their data. We created it

    so that you can improve your business flows, and interact with your customers

    and data in more innovative ways.



    Build something great!



    Once you've

    [registered your service account](https://yourdomain.fortifi.cloud/developers/service-accounts/) it's easy

    to start requesting and posting data to and from Fortifi.



    All endpoints are only accessible via https and are located at

    `api.fortifi.io`. For instance: you can grab a list of all your brands

    by accessing the following URL with your Access Token

    (replace ACCESS_TOKEN with your own):

    ```
      https://api.fortifi.io/v1/brands?access_token=ACCESS_TOKEN

    ```

    For non-GET requests, you must pass your ACCESS_TOKEN in the Authorization header else you will get an access denied
    response

    ```
        Authorization: Bearer ACCESS_TOKEN

    ```


    ## Limits

    Be nice. If you're sending too many requests too quickly, we'll send back a

    `503` error code (server unavailable).

    You are limited to 5000 requests per hour per `access_token`.



    ## Request Methods

    We do our best to have all URLs

    [RESTful](https://en.wikipedia.org/wiki/Representational_state_transfer).

    Every endpoint (URL) may support one of four different http verbs. GET

    requests fetch information about an object, POST requests create objects,

    PUT requests update objects, and finally DELETE requests will delete

    objects.



    ## Structure



    ### The Envelope

    Every response is contained by an envelope. That is, each response has a

    predictable set of keys with which you can expect to interact:

    ```json

    {
        'meta': {
            'code': 200
        },
        'data': {
            ...
        }
    }

    ```



    #### META

    The meta key is used to communicate extra information about the response to

    the developer. If all goes well, you'll only ever see a code key with

    value 200.

    However, sometimes things go wrong, and in that case you might see a

    response like:

    ```json

    {
        'meta': {
            'type': 'OAuthException',
            'code': 400,
            'message': '...'
        }
    }

    ```


    #### DATA

    The data key is the meat of the response. It may be a list or dictionary,

    but either way this is where you'll find the data you requested.

    #### JSONP

    If you're writing an AJAX application, and you'd like to wrap our response

    with a callback, all you have to do is specify a callback parameter with

    any API call:

    ```

    https://api.fortifi.io/v1/brands?access_token=ACCESS_TOKEN&callback=callbackFunction

    ```

    Would respond with:

    ```js

    callbackFunction({
        ...
    });

    ```
host: api.fortifi.io
schemes:
  - https
basePath: /v1
securityDefinitions:
  OAuth:
    type: oauth2
    tokenUrl: 'https://api.fortifi.io/oauth/token'
    flow: password
    scopes:
      'basic': Basic Read Access
      'visitor': Read/Write On Visitors
      'advertiser': Read/Write On Advertisers
      'customer': Read/Write On Customers
      'customer.readonly': Read Only on Customers
      'entity.properties': Read/Write On Entity Properties
      'entity.config': Read/Write On Entity Configuration
      'orders': Read/Write On Orders
      'orders.readonly': Read Only On Orders
      'products': Read/Write On Products
      'entity.events': Read/Write on Events
      'payment.methods': Read/Write On Payment Methods
      'contact': Read/Write On Contacts
      'polymer.readonly': Read Polymers
      'polymer': Read/Write On Polymers
      'product.readonly': Read Product Information
      'product': Read/Write On Products
      'purchase.readonly': Read Only on purchases
      'support': Read/Write On Support
      'support.readonly': Read Only on Support
      'reasons': Read/Write On reasons
      'reasons.readonly': Read Only on reasons
      'configuration.readonly': Read only for configuration
      'reservations': Read/Write reservations

  accessToken:
    type: apiKey
    in: query
    name: access_token

tags:
  - name: Authentication
  - name: Brands
  - name: Marketing
  - name: Customers
  - name: Entities
  - name: Orders
  - name: Payment Methods
  - name: Custom Properties
  - name: Configuration
  - name: Contacts
  - name: Polymers
  - name: Messenger
  - name: Products
  - name: Licence
  - name: Support
  - name: Service Status
  - name: Reasons
  - name: Events
  - name: Deprecated
  - name: Labels
  - name: Reservations
  - name: Finance

paths:
  '/account/verification':
    post:
      summary: Main Entry for Verification
      tags:
        - Account
      security:
        - OAuth:
            - account
        - accessToken: [ ]
  /accountant/transaction/search:
    post:
      tags:
        - Accountant
      security:
        - OAuth:
            - basic
        - accessToken: [ ]
      summary: Find an Account Transaction
      description: |
        Find an Account Transaction based on purchase information
  /advertisers:
    post:
      deprecated: true
      summary: Create a new advertiser
      security:
        - OAuth:
            - advertiser
        - accessToken: []
      tags:
        - Deprecated
    get:
      deprecated: true
      summary: List advertisers
      security:
        - OAuth:
            - advertiser
        - accessToken: []
      tags:
        - Deprecated
  /advertisers/{advertiserFid}:
    get:
      deprecated: true
      security:
        - OAuth:
            - advertiser
        - accessToken: []
      tags:
        - Deprecated
      summary: Retrieve an advertiser
  /advertisers/{advertiserFid}/approved:
    put:
      deprecated: true
      security:
        - OAuth:
            - advertiser
        - accessToken: []
      tags:
        - Deprecated
      summary: Set approved status on an advertiser
    delete:
      deprecated: true
      summary: Remove approved status on an advertiser
      tags:
        - Deprecated
      security:
        - OAuth:
            - advertiser
        - accessToken: []
  /advertisers/{advertiserFid}/campaigns:
    post:
      deprecated: true
      summary: Create a new advertiser campaign
      security:
        - OAuth:
            - advertiser
        - accessToken: []
      tags:
        - Deprecated
  /advertisers/{advertiserFid}/campaigns/{advertiserCampaignFid}:
    get:
      deprecated: true
      security:
        - OAuth:
            - advertiser
        - accessToken: []
      tags:
        - Deprecated
      summary: Retrieve an advertiser campaign
  /appstore/{customerFid}/google:
    post:
      tags:
        - Appstore
      security:
        - OAuth:
            - basic
        - accessToken: [ ]
      summary: Post a new Google notification
      description: |
        Post a new Google notification.
  /appstore/{customerFid}/apple:
    post:
      tags:
        - Appstore
      security:
        - OAuth:
            - basic
        - accessToken: [ ]
      summary: Post a new Apple notification
      description: |
        Post a new Apple notification.
  '/attachment/{entityFid}':
    post:
      summary: Create An Attachment
      tags:
        - attachment
      security:
        - OAuth:
            - attachment
        - accessToken: [ ]
  /brands:
    get:
      tags:
        - Brands
      security:
        - OAuth:
            - basic
        - accessToken: []
      summary: Your Brand
      operationId: getBrands
      description: |
        Retrieve a list of all the brands within your Fortifi account
  /presetChat:
    post:
      summary: Create a Preset Chat Instance
      tags:
        - Chat
      security:
        - OAuth:
            - chat
        - accessToken: [ ]
  /presetChat/{sessionId}:
    get:
      summary: Get a Preset Chat by ID
      tags:
        - Chat
      security:
        - OAuth:
            - chat
        - accessToken: [ ]
  /comments:
    post:
      summary: Apply a comment/note against a data-node
      tags:
        - Comments
      security:
        - OAuth:
            - comments
        - accessToken: [ ]
  /contacts/findByReference/{contactReference}:
    get:
      summary: Find a person with a reference
      tags:
        - Contacts
      security:
        - OAuth:
            - contact
        - accessToken: [ ]
  '/contacts/emails/{emailAddress}/confirm':
    put:
      summary: Confirm email address
      tags:
        - Contacts
      security:
        - OAuth:
            - contact
        - accessToken: [ ]
  '/contacts/emails/{emailAddress}/unsubscribe':
    put:
      summary: Unsubscribe an email address
      tags:
        - Contacts
      security:
        - OAuth:
            - contact
        - accessToken: [ ]
  '/contacts/emails/{emailAddress}/subscribe':
    put:
      summary: Subscribe an email address
      tags:
        - Contacts
      security:
        - OAuth:
            - contact
        - accessToken: [ ]
  '/contacts/phone/{phoneNumber}/confirm':
    put:
      summary: Confirm phone number
      tags:
        - Contacts
      security:
        - OAuth:
            - contact
        - accessToken: [ ]
  '/contacts/{contactFid}/addresses':
    get:
      summary: List contact addresses
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
    post:
      summary: Add an address to a contact
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/contacts/{contactFid}/addresses/{addressFid}':
    delete:
      summary: Remove an address from a contact
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/contacts/{contactFid}/emails':
    get:
      summary: List contact emails
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
    post:
      summary: Add an email address to a contact
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/contacts/{contactFid}/emails/{emailFid}':
    delete:
      summary: Remove an email from a contact
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/contacts/{contactFid}/phones':
    get:
      summary: List contact phones
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
    post:
      summary: Add a phone number to a contact
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/contacts/{contactFid}/phones/{phoneFid}':
    delete:
      summary: Remove a phone
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/contacts/device/{hardwareId}/unsubscribe':
    put:
      summary: Unsubscribe a device
      tags:
        - Contacts
      security:
        - OAuth:
            - contact
        - accessToken: [ ]
  '/contacts/device/{hardwareId}/subscribe':
    put:
      summary: Subscribe an device
      tags:
        - Contacts
      security:
        - OAuth:
            - contact
        - accessToken: [ ]
  '/customers/{customerFid}/payments/{paymentFid}/chargeback':
    post:
      summary: Initiate a chargeback on a payment
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: []
  '/customers/{customerFid}/chargebacks/{chargebackFid}':
    put:
      summary: Action a chargeback
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: []
  '/customers/{customerFid}/contacts':
    get:
      summary: List of people
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
    post:
      summary: Create a new contact for a customer
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/customers/{customerFid}/contacts/{contactFid}':
    put:
      summary: Update a contacts information
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
    get:
      summary: Retrieve information about a contact
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
    delete:
      summary: Remove a contact
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/customers/{customerFid}/addresses':
    get:
      summary: List customers addresses
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
    post:
      summary: Add an address to a customer
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/customers/{customerFid}/addresses/{addressFid}':
    delete:
      summary: Remove an address
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/customers/{customerFid}/emails':
    get:
      summary: List customers emails
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
    post:
      summary: Add an email address to a customer
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/customers/{customerFid}/emails/{emailFid}':
    delete:
      summary: Remove an email
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/customers/{customerFid}/phones':
    get:
      summary: List customers phones
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
    post:
      summary: Add a phone number to a customer
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/customers/{customerFid}/phones/{phoneFid}':
    delete:
      summary: Remove a phone
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/customers/{customerFid}/chatSessions':
    get:
      summary: Retrieve chat sessions for customer
      tags:
        - Customers
      security:
        - OAuth:
            - customer
            - customer.readonly
        - accessToken: [ ]
  '/customers/{customerFid}/interactions':
    post:
      summary: Create an interaction
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
    get:
      summary: List Customer interactions
      tags:
        - Customers
        - Interaction
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/customers/{customerFid}/tickets':
    post:
      summary: Create a new support ticket
      description: >
        The attachments property is an array of unique filenames that have been created using ```/upload/uploadUrl```
      tags:
        - Customers
        - Support
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
    get:
      summary: Get support tickets for customer
      tags:
        - Customers
        - Support
      security:
        - OAuth:
            - entity.config
        - accessToken: [ ]
  '/customers/{customerFid}/tickets/{ticketFid}/posts/{ticketPostTimestamp}/attachments':
    get:
      summary: Get attachments for a ticket post
      tags:
        - Customers
        - Support
      security:
        - OAuth:
            - entity.config
        - accessToken: [ ]
  '/customers/{customerFid}/tickets/{ticketFid}/posts':
    get:
      summary: Retrieve ticket posts for a ticket
      tags:
        - Customers
        - Support
      security:
        - OAuth:
            - entity.config
        - accessToken: [ ]
    post:
      summary: Post a reply to a ticket
      description: >
        The attachments property is an array of unique filenames that have been created using ```/upload/uploadUrl```
      tags:
        - Customers
        - Support
      security:
        - OAuth:
            - entity.config
        - accessToken: [ ]
  '/customers/{customerFid}/tickets/{ticketFid}':
    get:
      summary: Retrieve a single ticket for a customer
      tags:
        - Customers
        - Support
      security:
        - OAuth:
            - entity.config
        - accessToken: [ ]
  '/customers/{customerFid}/invoices':
    get:
      summary: List of invoice summaries for given customer
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/customers/{customerFid}/invoices/{invoiceFid}':
    get:
      summary: Retreive a specific itemised invoice
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/customers/{customerFid}/invoices/{invoiceFid}/download':
    get:
      summary: Retreive a specific itemised invoice PDF
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/customers/{customerFid}/invoices/retry':
    put:
      summary: Retry payment of all customer invoices which are in invoice
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/customers/{customerFid}/invoices/{invoiceFid}/retry':
    put:
      summary: Retry payment of invoice
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/customers/{customerFid}/invoices/{invoiceFid}/creditNote':
    post:
      summary: Add a credit note to a customers invoice
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/customers/{customerFid}/accountStatus':
    put:
      summary: Update a customers status
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/customers/{customerFid}/lifecycleStage':
    put:
      summary: Update a customers lifecycle stage
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/customers/{customerFid}/location':
    put:
      summary: Update a customers location
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/customers/{customerFid}/accountType':
    put:
      summary: Update a customers status
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/customers/{customerFid}/subscriptionType':
    put:
      summary: Update a customers status
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/customers/{customerFid}/qualified':
    put:
      summary: Mark customer as qualified, this action cannot be undone.
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/customers/{customerFid}/chargeback':
    put:
      summary: Mark customer as charged back, this action cannot be undone.
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/customers/{customerFid}/fraud':
    put:
      summary: Mark customer as fraudulent, this action cannot be undone.
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/customers/{customerFid}/purchased':
    put:
      summary: Mark customer as purchased, this action cannot be undone.
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/customers/{customerFid}/loyal':
    put:
      summary: Set customer loyalty flag
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
    delete:
      summary: Remove customer loyalty flag
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/customers/{customerFid}/vip':
    put:
      summary: Set customer as VIP
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
    delete:
      summary: Remove customer VIP Status
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/customers/{customerFid}/currency':
    put:
      summary: Set customer Currency
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/customers/{customerFid}/linkVisitor':
    put:
      summary: Link visitor to customer record
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/customers/{customerFid}/externalReference':
    put:
      summary: Update a customers external reference
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/customers/{customerFid}/note':
    post:
      summary: Save a note against a customer
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: []
  '/customers/{customerFid}/paymentAccounts':
    get:
      summary: List customers payment accounts
      tags:
        - Customers
        - Payment Methods
      security:
        - OAuth:
            - payment.methods
        - accessToken: []
  '/customers/{customerFid}/paymentAccounts/{paymentAccountFid}':
    get:
      summary: Retrieve payment account
      tags:
        - Customers
        - Payment Methods
      security:
        - OAuth:
            - payment.methods
        - accessToken: []
  '/customers/{customerFid}/paymentMethods':
    get:
      summary: List customers payment methods
      tags:
        - Customers
        - Payment Methods
      security:
        - OAuth:
            - payment.methods
        - accessToken: []
  '/customers/{customerFid}/paymentMethods/{paymentMethodFid}':
    get:
      summary: Retrieve a payment method
      tags:
        - Customers
        - Payment Methods
      security:
        - OAuth:
            - payment.methods
        - accessToken: []
    put:
      summary: Update a payment method
      tags:
        - Customers
        - Payment Methods
      security:
        - OAuth:
            - payment.methods
        - accessToken: []
    delete:
      summary: Archive a payment method
      tags:
        - Customers
        - Payment Methods
      security:
        - OAuth:
            - payment.methods
        - accessToken: [ ]
  '/customers/{customerFid}/paymentMethods/paypal/initialise':
    post:
      summary: Initialise a new paypal agreement for existing subscriptions
      tags:
        - Customers
        - Payment Methods
      security:
        - OAuth:
            - payment.methods
        - accessToken: []
  '/customers/{customerFid}/paymentMethods/paypal/complete':
    post:
      summary: Complete a paypal agreement created with initialise
      tags:
        - Customers
        - Payment Methods
      security:
        - OAuth:
            - payment.methods
        - accessToken: []
  '/customers/{customerFid}/paymentMethods/cards':
    get:
      summary: List customers card payment methods
      tags:
        - Customers
        - Payment Methods
      security:
        - OAuth:
            - payment.methods
        - accessToken: []
  '/customers/{customerFid}/paymentMethods/cards/{cardFid}':
    delete:
      tags:
        - Customers
        - Payment Methods
      security:
        - OAuth:
            - payment.methods
        - accessToken: []
    put:
      tags:
        - Customers
        - Payment Methods
      security:
        - OAuth:
            - payment.methods
        - accessToken: []
      summary: Update a card
  '/customers/{customerFid}/paymentMethods/cards/{cardFid}/lock':
    post:
      tags:
        - Customers
        - Payment Methods
      security:
        - OAuth:
            - payment.methods
        - accessToken: []
  '/customers/{customerFid}/paymentMethods/createPending':
    post:
      summary: Create a new pending payment method
      security:
        - OAuth:
            - payment
        - accessToken: [ ]
  '/customers/{customerFid}/payments/{paymentFid}':
    get:
      summary: Retrieve a payment
      tags:
        - Customers
      security:
        - OAuth:
            - customer
            - customer.readonly
        - accessToken: [ ]
  '/customers/{customerFid}/payments/{paymentFid}/refund':
    put:
      summary: Refund a payment
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/customers/{customerFid}/subscriptions':
    get:
      summary: List of subscription summaries for given customer
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/customers/{customerFid}/subscriptions/{subscriptionFid}':
    get:
      summary: Retreive a specific subscription
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
    put:
      summary: Update a subscription
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/customers/{customerFid}/subscriptions/{subscriptionFid}/periods':
    get:
      summary: Retreive the periods for a subscription
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/customers/{customerFid}/subscriptions/{subscriptionFid}/periods/{periodFid}/refund':
    put:
      summary: Refund a subscription period
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/customers/{customerFid}/subscriptions/{subscriptionFid}/enableAutoCharge':
    put:
      summary: Enable auto charge on specific subscription
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/customers/{customerFid}/subscriptions/{subscriptionFid}/disableAutoCharge':
    put:
      summary: Disable auto charge on specific subscription
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/customers/{customerFid}/subscriptions/{subscriptionFid}/autoCancelDays':
    put:
      summary: Set auto cancel days on a subscription
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/customers/{customerFid}/subscriptions/{subscriptionFid}/autoSuspendDays':
    put:
      summary: Set auto suspend days on a subscription
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/customers/{customerFid}/subscriptions/{subscriptionFid}/setAdvanceDays':
    put:
      summary: Set advance days on a subscription
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/customers/{customerFid}/subscriptions/{subscriptionFid}/renewalMode':
    put:
      summary: Set the renewal mode of a subscription
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/customers/{customerFid}/subscriptions/{subscriptionFid}/setParentSubscription':
    put:
      summary: Set parent subscription on a subscription
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/customers/{customerFid}/subscriptions/{subscriptionFid}/calculateModification':
    put:
      summary: Calculates the changes before a modification to a subscription
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/customers/{customerFid}/subscriptions/{subscriptionFid}/calculateRefund':
    put:
      summary: Calculates the result of a potential refund on a subscription
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/customers/{customerFid}/subscriptions/{subscriptionFid}/setPaymentAccount':
    put:
      summary: Set paymentAccount for subscription. If changing a payment method from an Automatic Payment Method such as PayPal Recurring Payments, any other subscriptions paid with the same Agreement will be set to Default Payment Method and the Agreement will be cancelled
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/customers/{customerFid}/subscriptions/{subscriptionFid}/modify':
    put:
      summary: Modify an existing subscription with a new price. Returns new open order to be completed
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/customers/{customerFid}/subscriptions/{subscriptionFid}/updateRenewalPrice':
    put:
      summary: Modify an existing subscription with a new price which will be used for the next renewal
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/customers/{customerFid}/subscriptions/{subscriptionFid}/applyOffer':
    put:
      summary: Apply an offer to a subscription
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/customers/{customerFid}/subscriptions/{subscriptionFid}/preRenew':
    put:
      summary: Pre-renew an existing subscription with a different price. Returns new open order to be completed
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/customers/{customerFid}/subscriptions/{subscriptionFid}/cancel':
    put:
      summary: Cancel a subscripion. Returns subscription FID.
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/customers/{customerFid}/subscriptions/{subscriptionFid}/reactivate':
    put:
      summary: Reactivate a subscription. Returns subscription FID.
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/customers/{customerFid}/subscriptions/{subscriptionFid}/allocations':
    get:
      summary: Retreive a subscriptions resource allocations
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/customers/{customerFid}/subscriptions/{subscriptionFid}/cancelFlow/reasons':
    get:
      summary: Retreive the available cancellation reasons for a subscription
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/customers/{customerFid}/subscriptions/{subscriptionFid}/cancelFlow/{flowSearch}/abandon':
    put:
      summary: Abandon a cancel flow
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/customers/{customerFid}/subscriptions/{subscriptionFid}/cancelFlow':
    get:
      summary: Retreive a list of active cancel flows
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
    post:
      summary: Start a cancel flow, and retrieve its state
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/customers/{customerFid}/subscriptions/{subscriptionFid}/cancelFlow/empty':
    post:
      summary: Create an empty cancel flow
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/customers/{customerFid}/subscriptions/{subscriptionFid}/cancelFlow/{flowSearch}':
    get:
      summary: Retreive the state of a cancel flow
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
    put:
      summary: Post an action for a cancel flow, and retrieve its latest state
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/customers/{customerFid}/subscriptions/{subscriptionFid}/cancelFlow/{flowSearch}/options':
    get:
      summary: Retrieve cancel flow options
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
    post:
      summary: Set cancel flow options
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/customers/{customerFid}/subscriptions/{subscriptionFid}/retentionFlow/reasons':
    get:
      summary: Retreive the available retention reasons for a subscription
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/customers/{customerFid}/subscriptions/{subscriptionFid}/retentionFlow/{flowSearch}/abandon':
    put:
      summary: Abandon a retention flow
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/customers/{customerFid}/subscriptions/{subscriptionFid}/retentionFlow':
    get:
      summary: Retreive a list of active retention flows
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
    post:
      summary: Start a retention flow, and retrieve its state
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/customers/{customerFid}/subscriptions/{subscriptionFid}/retentionFlow/empty':
    post:
      summary: Create an empty retention flow
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/customers/{customerFid}/subscriptions/{subscriptionFid}/retentionFlow/{flowSearch}':
    get:
      summary: Retreive the state of a retention flow
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
    put:
      summary: Post an action for a cancel flow, and retrieve its latest state
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/customers/{customerFid}/subscriptions/{subscriptionFid}/retentionFlow/{flowSearch}/options':
    get:
      summary: Retrieve retention flow options
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
    post:
      summary: Set retention flow options
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/customers/{customerFid}/subscriptions/{subscriptionFid}/provisioning/retry':
    put:
      summary: Retry the provisioning step
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/customers/{customerFid}/subscriptions/{subscriptionFid}/cancelRequest':
    post:
      summary: Create a cancel request for a subscription
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  '/customers/{customerFid}/orders':
    get:
      summary: List customer orders
      tags:
          - Customers
      security:
        - OAuth:
            - customer
        - accessToken: []
  '/customers/{customerFid}/billingData':
    put:
      summary: Update a customers billing data
      tags:
        - Customers
      security:
        - OAuth:
            - customer
        - accessToken: []
  '/customers/{customerFid}/sar':
    post:
      summary: Subject Access Request
      tags:
          - Customers
      description: |
        Initiate a Subject Access Request.  A URL will be sent via a webhook (CustomerWHE::SUBJECT_ACCESS_REQUEST), once the archive is ready for download
      security:
        - OAuth:
            - customer
        - accessToken: []
  '/customers/{customerFid}/anonymize':
    post:
      summary: Anonymize customer data
      tags:
        - Customers
      description: |
        Anonymize customer data
      security:
        - OAuth:
            - customer
        - accessToken: []
  '/customers/{customerFid}/sentEmails':
    get:
      summary: List Emails sent to a Customer
      tags:
        - Customers
        - Messenger
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
  /customers:
    post:
      summary: Create a new customer
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
      tags:
        - Customers
  /customers/findByReference:
    get:
      security:
        - OAuth:
            - customer
            - customer.readonly
        - accessToken: [ ]
      tags:
        - Customers
      summary: Find a customer by your reference
  /customers/findByEmail:
    get:
      security:
        - OAuth:
            - customer
            - customer.readonly
        - accessToken: [ ]
      tags:
        - Customers
      summary: Find a customer by brand and email address
  '/customers/{customerFid}':
    get:
      security:
        - OAuth:
            - customer
            - customer.readonly
        - accessToken: [ ]
      tags:
        - Customers
      summary: Retrieve a customer
    put:
      security:
        - OAuth:
            - customer
            - customer.readonly
        - accessToken: [ ]
      tags:
        - Customers
      summary: Update a customer
    delete:
      security:
        - OAuth:
            - customer
        - accessToken: [ ]
      tags:
        - Customers
      summary: Archive a customer
  '/customers/{customerFid}/upgradePaymentAccount':
    put:
      security:
        - OAuth:
            - customer
            - customer.readonly
        - accessToken: [ ]
      tags:
        - Customers
      summary: Upgrade customer from fortifi pay to chargehive
  '/device/upsert':
    post:
      summary: Create a Device or update and existing one
      tags:
        - Devices
      security:
        - OAuth:
            - device
        - accessToken: [ ]
  '/device/{hardwareId}':
    delete:
      summary: Remove a Device
      tags:
        - Devices
      security:
        - OAuth:
            - device
        - accessToken: [ ]
  '/entities/{entityFid}/config/{sectionName}':
    delete:
      summary: Remove a config section, or property from an entity
      tags:
        - Entities
        - Configuration
      security:
        - OAuth:
            - entity.config
        - accessToken: [ ]
    get:
      summary: Retrieve a config section
      tags:
        - Entities
        - Configuration
      security:
        - OAuth:
            - entity.config
        - accessToken: [ ]
    post:
      summary: Write a config item
      tags:
        - Entities
        - Configuration
      security:
        - OAuth:
            - entity.config
        - accessToken: [ ]
  '/entities/{entityFid}/config/{sectionName}/items/{itemName}':
    get:
      summary: Retrieve a config item
      tags:
        - Entities
        - Configuration
      security:
        - OAuth:
            - entity.config
        - accessToken: [ ]
  '/entities/{entityFid}/attachments/uploadUrl':
    post:
      summary: Create an upload url
      security:
        - OAuth:
            - entity.attachments
        - accessToken: [ ]
      tags:
        - Entities
  '/entities/{entityFid}/labels':
    get:
      summary: Get all labels for an entity
      tags:
        - Entities
        - Labels
      security:
        - OAuth:
            - entity.labels
        - accessToken: [ ]
  '/entities/{entityFid}/labels/assign':
    put:
      summary: Assign label to entity
      tags:
        - Entities
        - Labels
      security:
        - OAuth:
            - entity.labels
        - accessToken: [ ]
  '/entities/{entityFid}/properties':
    get:
      summary: Get all properties for an entity
      tags:
        - Entities
        - Custom Properties
      security:
        - OAuth:
            - entity.properties
        - accessToken: [ ]
    put:
      summary: Write multiple entity properties
      tags:
        - Entities
        - Custom Properties
      security:
        - OAuth:
            - entity.properties
        - accessToken: [ ]
  '/entities/{entityFid}/properties/values/{propertyName}':
    get:
      summary: Get a property value from an entity
      tags:
        - Entities
        - Custom Properties
      security:
        - OAuth:
            - entity.properties
        - accessToken: [ ]
    delete:
      summary: Remove a value property from an entity
      tags:
        - Entities
        - Custom Properties
      security:
        - OAuth:
            - entity.properties
        - accessToken: [ ]
    put:
      summary: Write an entity value property
      tags:
        - Entities
        - Custom Properties
      security:
        - OAuth:
            - entity.properties
        - accessToken: [ ]
  '/entities/{entityFid}/properties/flags/{propertyName}':
    get:
      summary: Get a flag property from an entity
      tags:
        - Entities
        - Custom Properties
      security:
        - OAuth:
            - entity.properties
        - accessToken: [ ]
    delete:
      summary: Remove a flag from an entity
      tags:
        - Entities
        - Custom Properties
      security:
        - OAuth:
            - entity.properties
        - accessToken: [ ]
    put:
      summary: Write an entity flag
      tags:
        - Entities
        - Custom Properties
      security:
        - OAuth:
            - entity.properties
        - accessToken: [ ]
  '/entities/{entityFid}/properties/counters/{propertyName}':
    delete:
      summary: Remove a counter from an entity
      tags:
        - Entities
        - Custom Properties
      security:
        - OAuth:
            - entity.properties
        - accessToken: [ ]
  '/entities/{entityFid}/properties/counters/{propertyName}/increment':
    put:
      summary: Increment an entity counter
      tags:
        - Entities
        - Custom Properties
      security:
        - OAuth:
            - entity.properties
        - accessToken: [ ]
  '/entities/{entityFid}/properties/counters/{propertyName}/decrement':
    put:
      summary: Decrement an entity counter
      tags:
        - Entities
        - Custom Properties
      security:
        - OAuth:
            - entity.properties
        - accessToken: [ ]
  '/entities/{entityFid}/events':
    post:
      summary: Trigger a new event
      tags:
        - Entities
        - Events
      security:
        - OAuth:
            - entity.events
        - accessToken: [ ]
  '/finance/payments':
    get:
      summary: Perform a payment search
      tags:
        - Finance
      security:
        - accessToken: [ ]
  '/flow/{flowFid}/log':
    post:
      summary: Create Flow
      tags:
        - Flow
      security:
        - OAuth:
            - flow
        - accessToken: [ ]
  '/interactions/journey':
    post:
      summary: Create A Customer Journey
      tags:
        - interactions
      security:
        - OAuth:
            - interactions
        - accessToken: [ ]
  '/interactions/{interactionFid}/client/connected':
    post:
      summary: A Client has connected to the Interaction
      tags:
        - interactions
      security:
        - OAuth:
            - interactions
        - accessToken: [ ]
  '/interactions/{interactionFid}/client/disconnected':
    post:
      summary: A Client has disconnected from the Interaction
      tags:
        - interactions
      security:
        - OAuth:
            - interactions
        - accessToken: [ ]
  '/interactions/{interactionFid}/message':
    post:
      summary: Add a message to a Interaction
      tags:
        - interactions
      security:
        - OAuth:
            - interactions
        - accessToken: [ ]
  '/interactions/{interactionFid}':
    get:
      summary: Get an interaction
      tags:
        - interactions
      security:
        - OAuth:
            - interactions
        - accessToken: [ ]
  '/interactions/{interactionFid}/messages':
    get:
      summary: Get all Messages on an interaction
      tags:
        - interactions
      security:
        - OAuth:
            - interactions
        - accessToken: [ ]
  '/interactions/{interactionFid}/feedback':
    post:
      summary: Submit Feedback to an interaction
      tags:
        - interactions
      security:
        - OAuth:
            - interactions
        - accessToken: [ ]
  '/interactions/invite':
    post:
      summary: Create an interaction Invite
      tags:
        - interactions
      security:
        - OAuth:
            - interactions
        - accessToken: [ ]
  '/interactions/invite/{inviteCode}':
    post:
      summary: Accept an interaction Invite
      tags:
        - interactions
      security:
        - OAuth:
            - interactions
        - accessToken: [ ]
  '/interactions/invite/{inviteCode}/status':
    get:
      summary: Get an interaction Invite Status
      tags:
        - interactions
      security:
        - OAuth:
            - interactions
        - accessToken: [ ]
  '/interactions/{interactionFid}/attachment':
    post:
      summary: Create an Interaction Attachment
      tags:
        - interactions
      security:
        - OAuth:
            - interactions
        - accessToken: [ ]
  '/interactions/{interactionFid}/customerClosed':
    post:
      summary: The Customer has purposely closed the interaction
      tags:
        - interactions
      security:
        - OAuth:
            - interactions
        - accessToken: [ ]
  '/licence/check':
    get:
      summary: Retrieve A Licence
      tags:
        - Licence
      security:
        - OAuth:
            - purchase.readonly
        - accessToken: []
  /me:
    get:
      summary: Current User
      tags:
        - Authentication
      security:
        - OAuth:
            - basic
        - accessToken: []
      operationId: getMe
      description: |
        Retrieve information about the current connected user (you)
  '/integrations/verifyUser':
    get:
      summary: Verify a user
      tags:
        - Authentication
      security:
        - accessToken: []
  '/messenger/deliveries/{deliveryFid}/unsubscribe':
    put:
      summary: Unsubscribe an email based on the delivery fid
      tags:
        - Messenger
        - Contacts
      security:
        - OAuth:
            - contact
        - accessToken: []
  '/messenger/deliveries/{deliveryFid}/subscribe':
    put:
      summary: Subscribe an email based on the delivery fid
      tags:
        - Contacts
        - Messenger
      security:
        - OAuth:
            - contact
        - accessToken: []
  /orders:
    post:
      summary: Create a new order
      tags:
        - Orders
      security:
        - OAuth:
            - orders
        - accessToken: [ ]
  '/orders/{orderFid}':
    get:
      summary: Retrieve an order
      tags:
        - Orders
      security:
        - OAuth:
            - orders.readonly
        - accessToken: [ ]
  '/orders/{orderFid}/items':
    get:
      summary: List an orders items
      tags:
        - Orders
      security:
        - OAuth:
            - orders.readonly
        - accessToken: [ ]
  '/orders/{orderFid}/items/{productFid}/{orderItemFid}':
    put:
      summary: Update an order item
      tags:
        - Orders
      security:
        - OAuth:
            - orders
        - accessToken: [ ]
  '/orders/{orderFid}/verify':
    put:
      summary: Verify an order, returning any security urls
      tags:
        - Orders
      security:
        - OAuth:
            - orders
        - accessToken: [ ]
  '/orders/{orderFid}/cancel':
    put:
      summary: Cancel an order
      tags:
        - Orders
      security:
        - OAuth:
            - orders
        - accessToken: [ ]
  '/orders/{orderFid}/finalize':
    put:
      summary: Mark an order as finalized
      tags:
        - Orders
      security:
        - OAuth:
            - orders
        - accessToken: [ ]
  '/orders/{orderFid}/confirmCard':
    put:
      summary: Confirm an order, authorize the payment
      tags:
        - Orders
      security:
        - OAuth:
            - orders
        - accessToken: [ ]
  '/orders/{orderFid}/confirmPayPal':
    put:
      summary: Confirm an order, authorize the payment
      tags:
        - Orders
      security:
        - OAuth:
            - orders
        - accessToken: [ ]
  '/orders/{orderFid}/setChargeId':
    put:
      summary: Set a ChargeHive.com Charge ID on an order
      tags:
        - Orders
      security:
        - OAuth:
            - orders
        - accessToken: [ ]
  '/orders/{orderFid}/externalReference':
    put:
      summary: Set the external reference on an order
      tags:
        - Orders
      security:
        - OAuth:
            - orders
        - accessToken: [ ]
  '/orders/{orderFid}/fraudScan':
    get:
      summary: Retrieve fraud scan
      tags:
        - Orders
      security:
        - OAuth:
            - orders.readonly
        - accessToken: [ ]
  '/orders/{orderFid}/triggerOnDemand':
    put:
      summary: Trigger OnDemand schedule for an order
      tags:
        - Orders
      security:
        - OAuth:
            - orders
        - accessToken: [ ]
  '/orders/{orderFid}/products':
    get:
      summary: Retrieve order products
      tags:
        - Orders
      security:
        - OAuth:
            - orders.readonly
        - accessToken: [ ]
    post:
      summary: Add a product to an order
      tags:
        - Orders
      security:
        - OAuth:
            - orders
        - accessToken: [ ]
    put:
      summary: Set the products on an order
      tags:
        - Orders
      security:
        - OAuth:
            - orders
        - accessToken: [ ]
  '/orders/{orderFid}/products/{orderProductFid}':
    delete:
      summary: Remove a product from an order
      tags:
        - Orders
      security:
        - OAuth:
            - orders
        - accessToken: [ ]
  '/orders/{orderFid}/products/{orderProductFid}/quantity':
    put:
      summary: Set the quantity of a product on an order
      tags:
        - Orders
      security:
        - OAuth:
            - orders
        - accessToken: [ ]
  '/orders/{orderFid}/offers':
    post:
      summary: Add an offer to an order
      tags:
        - Orders
      security:
        - OAuth:
            - orders
        - accessToken: [ ]
  '/orders/{orderFid}/offers/{offerFid}':
    delete:
      summary: Remove an offer from an order
      tags:
        - Orders
      security:
        - OAuth:
            - orders
        - accessToken: [ ]
  '/orders/{orderFid}/products/{orderProductFid}/setInitialTerm':
    put:
      summary: Set the initial term of a product on an order
      tags:
        - Orders
      security:
        - OAuth:
            - orders
        - accessToken: [ ]
  /organisation:
    get:
      summary: Current Organisation
      tags:
        - Authentication
      security:
        - OAuth:
            - basic
        - accessToken: []
      operationId: getOrganisation
      description: |
        Retrieve information about the current organisation
  '/payments/transaction/{transactionId}':
    get:
      summary: Retrieve a payment by transaction ID
      tags:
        - Customers
      security:
        - OAuth:
            - customer
            - customer.readonly
        - accessToken: [ ]
  '/polymers/{parentFid}':
    post:
      summary: Create a new polymer
      tags:
        - Polymers
      security:
        - OAuth:
            - polymer
        - accessToken: [ ]
  '/polymers/{parentFid}/{polymerFid}':
    get:
      summary: Read a polymer
      tags:
        - Polymers
      security:
        - OAuth:
            - polymer.readonly
        - accessToken: [ ]
  '/polymers/list/{code}/{parentFid}':
    get:
      summary: List polymers by type
      tags:
        - Polymer
      security:
        - OAuth:
            - polymer.readonly
        - accessToken: [ ]
  /products:
    get:
      summary: List all products
      tags:
        - Products
      security:
        - OAuth:
            - product.readonly
        - accessToken: [ ]
  '/products/{productFid}/availability/check':
    post:
      summary: Check Product Availability
      tags:
        - Products
      security:
        - OAuth:
            - product.readonly
        - accessToken: [ ]
  '/products/{productFid}/availability/reserve':
    post:
      summary: Reserve Product
      tags:
        - Products
      security:
        - OAuth:
            - product.readonly
        - accessToken: [ ]
  '/products/{productFid}/prices':
    get:
      summary: Retrieve Product Prices
      tags:
        - Products
      security:
        - OAuth:
            - product.readonly
        - accessToken: [ ]
  '/products/{productFid}/pricebands':
    get:
      summary: Retrieve Product Price Bands
      tags:
        - Products
      security:
        - OAuth:
            - product.readonly
        - accessToken: [ ]
  '/products/{productFid}/skus':
    get:
      summary: Retrieve Product SKUs
      tags:
        - Products
      security:
        - OAuth:
            - product.readonly
        - accessToken: [ ]
  '/products/groups':
    get:
      summary: Get a list of all product groups
      tags:
        - Products
      security:
        - OAuth:
            - product.readonly
        - accessToken: [ ]
  '/products/groups/{productGroupFid}/products':
    get:
      summary: Get a list of products belonging to the group
      tags:
        - Products
      security:
        - OAuth:
            - product.readonly
        - accessToken: [ ]
  '/products/offers':
    get:
      summary: Retrieve all offers
      tags:
        - Products
      security:
        - OAuth:
            - product.readonly
        - accessToken: [ ]
  '/properties':
    get:
      summary: Get defined properties
      tags:
        - Properties
      security:
        - OAuth:
            - properties.readonly
        - accessToken: []
  /publishers:
    post:
      summary: Create a new publisher
      security:
        - OAuth:
            - publisher
        - accessToken: [ ]
      tags:
        - Marketing
    get:
      summary: List publishers
      security:
        - OAuth:
            - publisher
        - accessToken: [ ]
      tags:
        - Marketing
  /publishers/{publisherFid}:
    get:
      security:
        - OAuth:
            - publisher
        - accessToken: [ ]
      tags:
        - Marketing
      summary: Retrieve a publisher
    delete:
      summary: Delete a publisher
      security:
        - OAuth:
            - publisher
        - accessToken: [ ]
      tags:
        - Marketing
  /publishers/{publisherFid}/restore:
    put:
      summary: Restore a publisher
      security:
        - OAuth:
            - publisher
        - accessToken: [ ]
      tags:
        - Marketing
  /publishers/{publisherFid}/enable:
    put:
      summary: Enable a publisher
      security:
        - OAuth:
            - publisher
        - accessToken: [ ]
      tags:
        - Marketing
  /publishers/{publisherFid}/disable:
    put:
      summary: Disable a publisher
      security:
        - OAuth:
            - publisher
        - accessToken: [ ]
      tags:
        - Marketing
  /publishers/{publisherFid}/approved:
    put:
      security:
        - OAuth:
            - publisher
        - accessToken: [ ]
      tags:
        - Marketing
      summary: Set approved status on an publisher
    delete:
      summary: Remove approved status on an publisher
      tags:
        - Marketing
      security:
        - OAuth:
            - publisher
        - accessToken: [ ]
  /publishers/{publisherFid}/campaigns:
    get:
      summary: List campaigns
      security:
        - OAuth:
            - publisher
        - accessToken: [ ]
      tags:
        - Marketing
    post:
      summary: Create a new publisher campaign
      security:
        - OAuth:
            - publisher
        - accessToken: [ ]
      tags:
        - Marketing
  /publishers/{publisherFid}/campaigns/{publisherCampaignFid}:
    get:
      security:
        - OAuth:
            - publisher
        - accessToken: [ ]
      tags:
        - Marketing
      summary: Retrieve a publisher campaign
  /publishers/{publisherFid}/finance/costImport:
    post:
      summary: Import cost data
      security:
        - OAuth:
            - publisher
        - accessToken: [ ]
      tags:
        - Finance
  /publishers/{publisherFid}/finance/costImport/{costImportFid}:
    get:
      summary: Retrieve the status of cost import
      security:
        - OAuth:
            - publisher
        - accessToken: [ ]
      tags:
        - Finance
  '/reasons/groups':
    get:
      summary: Get a list of all reason groups
      tags:
          - Reasons
      security:
        - OAuth:
            - reasons.readonly
        - accessToken: []
  '/reasons/groups/{reasonGroupFid}':
    get:
      summary: Get all the reasons for the reason group
      tags:
        - Reasons
      security:
        - OAuth:
            - reasons.readonly
        - accessToken: []
  '/reservations/{key}/{application}/{brandFid}':
    get:
      security:
        - OAuth:
            - reservations
        - accessToken: [ ]
      tags:
        - Reservations
      summary: Retrieve reservations
      description: This call will return information related to how a visitor arrived
  '/reservations/{key}/{application}/{brandFid}/{customerFid}':
    post:
      security:
        - OAuth:
            - reservations
        - accessToken: [ ]
      tags:
        - Reservations
      summary: Make a new reservation
      description: Reserve against a key
  '/review':
    post:
      summary: Create a new Review and Review audit
      tags:
        - Reviews
      security:
        - OAuth:
            - review
        - accessToken: [ ]
    put:
      summary: Update a Review
      tags:
        - Reviews
      security:
        - OAuth:
            - review
        - accessToken: [ ]
  '/services':
    get:
      summary: Retrieve all services
      tags:
          - Service Status
      security:
        - OAuth:
            - entity.properties
        - accessToken: []
  '/services/{serviceFid}/incidents':
    get:
      summary: Retrieve incidents for service within timeframe
      tags:
        - Service Status
      security:
        - OAuth:
            - entity.properties
        - accessToken: []
  '/services/{serviceFid}/incidents/{incidentFid}/updates':
    get:
      summary: Retrieve incident updates for incident
      tags:
        - Service Status
      security:
        - OAuth:
            - entity.properties
        - accessToken: []
  /svcauth/verify:
    post:
      summary: Verify service account / Get Access Token
      tags:
        - Authentication
      operationId: getServiceAuthToken
      description: |
        User service account credentials to retrieve an API token
  '/tickets':
    post:
      summary: Create a support ticket
      description: >
        The attachments property is an array of unique filenames that have been created using ```/upload/uploadUrl```
      tags:
        - Support
      security:
        - OAuth:
            - support
        - accessToken: [ ]
  '/tickets/{ticketFid}':
    get:
      summary: Get a ticket
      tags:
        - Support
      security:
        - OAuth:
            - support
        - accessToken: [ ]
  '/tickets/{ticketFid}/status':
    put:
      summary: Set the status of a ticket
      tags:
        - Support
      security:
        - OAuth:
            - support
        - accessToken: [ ]
  '/tickets/{ticketFid}/posts':
    get:
      summary: Retrieve ticket posts for a ticket
      tags:
        - Support
      security:
        - OAuth:
            - entity.config
        - accessToken: [ ]
  '/tickets/{ticketFid}/note':
    post:
      summary: Create a note against the ticket
      tags:
        - Support
      security:
        - OAuth:
            - support
        - accessToken: [ ]
  '/upload/uploadUrl':
    post:
      summary: Create an upload attachment url
      description: >
        This call will give you a URL to PUT files to and a unique filename.
        You can upload files to the URL like this:
        ```curl -X PUT -d @filename -H 'content-type: text/plain' 'url'```
      security:
        - OAuth:
            - attachments
        - accessToken: []
      tags:
        - Entities
  /version:
    get:
      summary: Current Version
      tags:
        - Authentication
      security:
        - OAuth:
            - basic
        - accessToken: []
      operationId: getVersion
      description: |
        Retrieve the current version of the Fortifi api
  '/visitors/{visitorId}':
    get:
      security:
        - OAuth:
            - visitor
        - accessToken: []
      tags:
          - Marketing
      summary: Retrieve information about a visitor
      description: This call will return information related to how a visitor arrived
  '/visitors/{visitorId}/pixels':
    get:
      security:
        - OAuth:
            - visitor
        - accessToken: []
      tags:
        - Marketing
      summary: Retrieve pending pixels for this visitor
      description: This call will release pixels from the pending queue on read
  '/visitors/{visitorId}/actions/{actionKey}':
    post:
      summary: Track an action
      tags:
        - Marketing
      description: |
        Track an action such as a lead or acquisition
      security:
        - OAuth:
            - visitor
        - accessToken: []
  '/visitors/{visitorId}/actions/{actionKey}/reverse':
    post:
      summary: Reverse a previously tracked action
      tags:
        - Marketing
      description: |
        When an action has been reversed, e.g. cancelled, refunded
      security:
        - OAuth:
            - visitor
        - accessToken: []