swagger: '2.0'
info:
  title: Fortifi API
  version: '3.17.1'
  termsOfService: 'http://fortifi.io/legal/terms/api'
  description: >
    The second version of the Fortifi API is an exciting step forward towards

    making it easier for businesses to have open access to their data. We created it

    so that you can improve your business flows, and interact with your customers

    and data in more innovative ways.



    Build something great!



    Once you've

    [registered your service account](http://yourdomain.fortifi.it/developers/service-accounts/) it's easy

    to start requesting and posting data to and from Fortifi.



    All endpoints are only accessible via https and are located at

    `api.fortifi.io`. For instance: you can grab a list of all your brands

    by accessing the following URL with your Access Token

    (replace ACCESS_TOKEN with your own):

    ```
      https://api.fortifi.io/v1/brands?access_token=ACCESS_TOKEN

    ```


    ## Limits

    Be nice. If you're sending too many requests too quickly, we'll send back a

    `503` error code (server unavailable).

    You are limited to 5000 requests per hour per `access_token`.



    ## Request Methods

    We do our best to have all URLs

    [RESTful](http://en.wikipedia.org/wiki/Representational_state_transfer).

    Every endpoint (URL) may support one of four different http verbs. GET

    requests fetch information about an object, POST requests create objects,

    PUT requests update objects, and finally DELETE requests will delete

    objects.



    ## Structure



    ### The Envelope

    Every response is contained by an envelope. That is, each response has a

    predictable set of keys with which you can expect to interact:

    ```json

    {
        'meta': {
            'code': 200
        },
        'data': {
            ...
        }
    }

    ```



    #### META

    The meta key is used to communicate extra information about the response to

    the developer. If all goes well, you'll only ever see a code key with

    value 200.

    However, sometimes things go wrong, and in that case you might see a

    response like:

    ```json

    {
        'meta': {
            'type': 'OAuthException',
            'code': 400,
            'message': '...'
        }
    }

    ```


    #### DATA

    The data key is the meat of the response. It may be a list or dictionary,

    but either way this is where you'll find the data you requested.

    #### JSONP

    If you're writing an AJAX application, and you'd like to wrap our response

    with a callback, all you have to do is specify a callback parameter with

    any API call:

    ```

    https://api.fortifi.io/v1/brands?access_token=ACCESS_TOKEN&callback=callbackFunction

    ```

    Would respond with:

    ```js

    callbackFunction({
        ...
    });

    ```
host: api.fortifi.io
schemes:
  - https
basePath: /v1
tags:
  - name: Marketing
  - name: Customers
  - name: Entities
  - name: Orders
  - name: Custom Properties
  - name: Configuration
  - name: Contacts
  - name: Polymers
  - name: Messenger
  - name: Products
  - name: Licence
  - name: Support
  - name: ServiceStatus
  - name: Reasons

securityDefinitions:
  OAuth:
    type: oauth2
    authorizationUrl: 'https://api.fortifi.io/oauth/authorize'
    tokenUrl: 'https://api.fortifi.io/oauth/token'
    flow: accessCode
    scopes:
      'basic': Basic Read Access
      'visitor': Read/Write On Visitors
      'advertiser': Read/Write On Advertisers
      'customer': Read/Write On Customers
      'customer.readonly': Read Only on Customers
      'entity.properties': Read/Write On Entity Properties
      'entity.config': Read/Write On Entity Configuration
      'orders': Read/Write On Orders
      'orders.readonly': Read Only On Orders
      'products': Read/Write On Products
      'entity.events': Read/Write on Events
      'payment.methods': Read/Write On Payment Methods
      'contact': Read/Write On Contacts
      'polymer.readonly': Read Polymers
      'polymer': Read/Write On Polymers
      'product.readonly': Read Product Information
      'product': Read/Write On Products
      'purchase.readonly': Read Only on purchases
      'support': Read/Write On Support
      'support.readonly': Read Only on Support
      'reasons': Read/Write On reasons
      'reasons.readonly': Read Only on reasons
      'configuration.readonly': Read only for configuration

  accessToken:
    type: apiKey
    in: query
    name: access_token

paths:
  /version:
    get:
      security:
        - OAuth:
            - basic
        - accessToken: []
      summary: Current Version
      operationId: getVersion
      description: |
        Retrieve the current version of the Fortifi api
  /svcauth/verify:
    post:
      summary: Verify service account / Get Access Token
      operationId: getServiceAuthToken
      description: |
        User service account credentials to retrieve an API token
  /me:
    get:
      security:
        - OAuth:
            - basic
        - accessToken: []
      summary: Current User
      operationId: getMe
      description: |
        Retrieve information about the current connected user (you)
  /organisation:
    get:
      security:
        - OAuth:
            - basic
        - accessToken: []
      summary: Current Organisation
      operationId: getOrganisation
      description: |
        Retrieve information about the current organisation
  /brands:
    get:
      security:
        - OAuth:
            - basic
        - accessToken: []
      summary: Your Brand
      operationId: getBrands
      description: |
        Retrieve a list of all the brands within your Fortifi account
  /advertisers:
    post:
      summary: Create a new advertiser
      security:
        - OAuth:
            - advertiser
        - accessToken: []
      tags:
        - marketing
    get:
      summary: List advertisers
      security:
        - OAuth:
            - advertiser
        - accessToken: []
      tags:
        - marketing
  /advertisers/{advertiserFid}:
    get:
      security:
        - OAuth:
            - advertiser
        - accessToken: []
      tags:
        - marketing
      summary: Retrieve an advertiser
  /advertisers/{advertiserFid}/approved:
    put:
      security:
        - OAuth:
            - advertiser
        - accessToken: []
      tags:
        - marketing
      summary: Set approved status on an advertiser
    delete:
      summary: Remove approved status on an advertiser
      tags:
        - marketing
      security:
        - OAuth:
            - advertiser
        - accessToken: []
  /advertisers/{advertiserFid}/campaigns:
    post:
      summary: Create a new advertiser campaign
      security:
        - OAuth:
            - advertiser
        - accessToken: []
      tags:
        - marketing
  /advertisers/{advertiserFid}/campaigns/{advertiserCampaignFid}:
    get:
      security:
        - OAuth:
            - advertiser
        - accessToken: []
      tags:
        - marketing
      summary: Retrieve an advertiser campaign
  '/visitors/{visitorId}':
    get:
      security:
        - OAuth:
            - visitor
        - accessToken: []
      tags:
        - marketing
      summary: Retrieve information about a visitor
      description: This call will return information related to how a visitor arrived
  '/visitors/{visitorId}/pixels':
    get:
      security:
        - OAuth:
            - visitor
        - accessToken: []
      tags:
        - marketing
      summary: Retrieve pending pixels for this visitor
      description: This call will release pixels from the pending queue on read
  '/visitors/{visitorId}/actions/{actionKey}':
    post:
      summary: Track an action
      tags:
        - marketing
      description: |
        Track an action such as a lead or acquisition
      security:
        - OAuth:
            - visitor
        - accessToken: []
  '/visitors/{visitorId}/actions/{actionKey}/reverse':
    post:
      summary: Reverse a previously tracked action
      tags:
        - marketing
      description: |
        When an action has been reversed, e.g. cancelled, refunded
      security:
        - OAuth:
            - visitor
        - accessToken: []
  /pay/publicKey:
    get:
      summary: Get the public key needed to encrypt a credit card number
      security:
        - OAuth:
            - payment.methods
        - accessToken: []
  /pay/coinbase:
    get:
      summary: Get a new checkout ID
      security:
        - OAuth:
            - payment.methods
        - accessToken: []
  /customers:
    post:
      summary: Create a new customer
      security:
        - OAuth:
            - customer
        - accessToken: []
      tags:
        - customers
  /customers/findByReference:
    get:
      security:
        - OAuth:
            - customer
            - customer.readonly
        - accessToken: []
      tags:
        - customers
      summary: Find a customer by your reference
  '/customers/{customerFid}':
    get:
      security:
        - OAuth:
            - customer
            - customer.readonly
        - accessToken: []
      tags:
        - customers
      summary: Retrieve a customer
    put:
      security:
        - OAuth:
            - customer
            - customer.readonly
        - accessToken: []
      tags:
        - customers
      summary: Update a customer
    delete:
      security:
        - OAuth:
            - customer
        - accessToken: []
      tags:
        - customers
      summary: Archive a customer
  '/customers/{customerFid}/accountStatus':
    put:
      summary: Update a customers status
      tags:
        - customers
      security:
        - OAuth:
            - customer
        - accessToken: []
  '/customers/{customerFid}/lifecycleStage':
    put:
      summary: Update a customers lifecycle stage
      tags:
        - customers
      security:
        - OAuth:
            - customer
        - accessToken: []
  '/customers/{customerFid}/note':
    post:
      summary: Save a note against a customer
      tags:
        - customers
      security:
        - OAuth:
            - customer
        - accessToken: []
  '/customers/{customerFid}/location':
    put:
      summary: Update a customers location
      tags:
        - customers
      security:
        - OAuth:
            - customer
        - accessToken: []
  '/customers/{customerFid}/accountType':
    put:
      summary: Update a customers status
      tags:
        - customers
      security:
        - OAuth:
            - customer
        - accessToken: []
  '/customers/{customerFid}/subscriptionType':
    put:
      summary: Update a customers status
      tags:
        - customers
      security:
        - OAuth:
            - customer
        - accessToken: []
  '/customers/{customerFid}/qualified':
    put:
      summary: Mark customer as qualified, this action cannot be undone.
      tags:
        - customers
      security:
        - OAuth:
            - customer
        - accessToken: []
  '/customers/{customerFid}/chargeback':
    put:
      summary: Mark customer as charged back, this action cannot be undone.
      tags:
        - customers
      security:
        - OAuth:
            - customer
        - accessToken: []
  '/customers/{customerFid}/fraud':
    put:
      summary: Mark customer as fraudulent, this action cannot be undone.
      tags:
        - customers
      security:
        - OAuth:
            - customer
        - accessToken: []
  '/customers/{customerFid}/purchased':
    put:
      summary: Mark customer as purchased, this action cannot be undone.
      tags:
        - customers
      security:
        - OAuth:
            - customer
        - accessToken: []
  '/customers/{customerFid}/loyal':
    put:
      summary: Set customer loyalty flag
      tags:
        - customers
      security:
        - OAuth:
            - customer
        - accessToken: []
    delete:
      summary: Remove customer loyalty flag
      tags:
        - customers
      security:
        - OAuth:
            - customer
        - accessToken: []
  '/customers/{customerFid}/vip':
    put:
      summary: Set customer as VIP
      tags:
        - customers
      security:
        - OAuth:
            - customer
        - accessToken: []
    delete:
      summary: Remove customer VIP Status
      tags:
        - customers
      security:
        - OAuth:
            - customer
        - accessToken: []
  '/customers/{customerFid}/currency':
    put:
      summary: Set customer Currency
      tags:
        - customers
      security:
        - OAuth:
            - customer
        - accessToken: []
  '/customers/{customerFid}/chatSessions':
    get:
      summary: Retrieve chat sessions for customer
      tags:
        - customers
      security:
        - OAuth:
            - customer
            - customer.readonly
        - accessToken: []
  '/customers/{customerFid}/payments/{paymentFid}':
    get:
      summary: Retrieve a payment
      tags:
        - customers
      security:
        - OAuth:
            - customer
            - customer.readonly
        - accessToken: []
  '/customers/{customerFid}/payments/{paymentFid}/refund':
    put:
      summary: Refund a payment
      tags:
        - customers
      security:
        - OAuth:
            - customer
        - accessToken: []
  '/customers/{customerFid}/contacts':
    get:
      summary: List contacts
      tags:
        - customers
      security:
        - OAuth:
            - customer
        - accessToken: []
    post:
      summary: Create a new contact for a customer
      tags:
        - customers
      security:
        - OAuth:
            - customer
        - accessToken: []
  '/customers/{customerFid}/contacts/{contactFid}':
    put:
      summary: Update a contacts information
      tags:
        - customers
      security:
        - OAuth:
            - customer
        - accessToken: []
    get:
      summary: Retrieve information about a contact
      tags:
        - customers
      security:
        - OAuth:
            - customer
        - accessToken: []
    delete:
      summary: Remove a contact
      tags:
        - customers
      security:
        - OAuth:
            - customer
        - accessToken: []
  '/customers/{customerFid}/linkVisitor':
    put:
      summary: Link visitor to customer record
      tags:
        - customers
      security:
        - OAuth:
            - customer
        - accessToken: []
  '/customers/{customerFid}/payments/{paymentFid}/chargeback':
    post:
      summary: Initiate a chargeback on a payment
      tags:
        - customers
      security:
        - OAuth:
            - customer
        - accessToken: []
  '/customers/{customerFid}/chargebacks/{chargebackFid}':
    put:
      summary: Action a chargeback
      tags:
        - customers
      security:
        - OAuth:
            - customer
        - accessToken: []
  '/customers/{customerFid}/tickets':
    post:
      summary: Create a new support ticket
      tags:
        - customers
        - support
      security:
        - OAuth:
            - customer
        - accessToken: []
    get:
      summary: Get support tickets for customer
      tags:
        - customers
        - support
      security:
        - OAuth:
            - entity.config
        - accessToken: []
  '/entities/{entityFid}/config/{sectionName}':
    delete:
      summary: Remove a config section, or property from an entity
      tags:
        - Configuration
      security:
        - OAuth:
            - entity.config
        - accessToken: []
    get:
      summary: Retrieve a config section
      tags:
        - Configuration
      security:
        - OAuth:
            - entity.config
        - accessToken: []
    post:
      summary: Write a config item
      tags:
        - Configuration
      security:
        - OAuth:
            - entity.config
        - accessToken: []
  '/entities/{entityFid}/config/{sectionName}/items/{itemName}':
    get:
      summary: Retrieve a config item
      tags:
        - Configuration
      security:
        - OAuth:
            - entity.config
        - accessToken: []
  '/entities/{entityFid}/attachments/uploadUrl':
    post:
      summary: Create an upload url
      security:
        - OAuth:
            - entity.attachments
        - accessToken: []
      tags:
        - entity
  '/entities/{entityFid}/properties':
    put:
      summary: Write multiple entity properties
      tags:
        - Custom Properties
      security:
        - OAuth:
            - entity.properties
        - accessToken: []
  '/entities/{entityFid}/properties/values/{propertyName}':
    get:
      summary: Get a property value from an entity
      tags:
        - Custom Properties
      security:
        - OAuth:
            - entity.properties
        - accessToken: []
    delete:
      summary: Remove a value property from an entity
      tags:
        - Custom Properties
      security:
        - OAuth:
            - entity.properties
        - accessToken: []
    put:
      summary: Write an entity value property
      tags:
        - Custom Properties
      security:
        - OAuth:
            - entity.properties
        - accessToken: []
  '/entities/{entityFid}/properties/flags/{propertyName}':
    delete:
      summary: Remove a flag from an entity
      tags:
        - Custom Properties
      security:
        - OAuth:
            - entity.properties
        - accessToken: []
    put:
      summary: Write an entity flag
      tags:
        - Custom Properties
      security:
        - OAuth:
            - entity.properties
        - accessToken: []
  '/entities/{entityFid}/properties/counters/{propertyName}':
    delete:
      summary: Remove a counter from an entity
      tags:
        - Custom Properties
      security:
        - OAuth:
            - entity.properties
        - accessToken: []
  '/entities/{entityFid}/properties/counters/{propertyName}/increment':
    put:
      summary: Increment an entity counter
      tags:
        - Custom Properties
      security:
        - OAuth:
            - entity.properties
        - accessToken: []
  '/entities/{entityFid}/properties/counters/{propertyName}/decrement':
    put:
      summary: Decrement an entity counter
      tags:
        - Custom Properties
      security:
        - OAuth:
            - entity.properties
        - accessToken: []
  '/entities/{entityFid}/events':
    post:
      summary: Trigger a new event
      security:
        - OAuth:
            - entity.events
        - accessToken: []
  '/customers/{customerFid}/paymentAccounts':
    get:
      summary: List customers payment accounts
      tags:
        - customers
        - payment.methods
      security:
        - OAuth:
            - payment.methods
        - accessToken: []
  '/customers/{customerFid}/paymentMethods/paypal/initialise':
    post:
      summary: Initialise a new paypal agreement for existing subscriptions
      tags:
        - customers
        - payment.methods
      security:
        - OAuth:
            - payment.methods
        - accessToken: []
  '/customers/{customerFid}/paymentMethods/paypal/complete':
    post:
      summary: Complete a paypal agreement created with initialise
      tags:
        - customers
        - payment.methods
      security:
        - OAuth:
            - payment.methods
        - accessToken: []
  '/customers/{customerFid}/paymentMethods/cards':
    post:
      summary: Add a new card
      tags:
        - customers
        - paymentMethods
      security:
        - OAuth:
            - payment.methods
        - accessToken: []
    get:
      summary: List customers card payment methods
      tags:
        - customers
        - payment.methods
      security:
        - OAuth:
            - payment.methods
        - accessToken: []
  '/customers/{customerFid}/paymentMethods/cards/{cardFid}':
    delete:
      tags:
        - customers
        - paymentMethods
      security:
        - OAuth:
            - payment.methods
        - accessToken: []
    put:
      tags:
        - customers
        - paymentMethods
      security:
        - OAuth:
            - payment.methods
        - accessToken: []
      summary: Update a card
  '/customers/{customerFid}/addresses':
    get:
      summary: List customers addresses
      tags:
        - customers
      security:
        - OAuth:
            - customer
        - accessToken: []
    post:
      summary: Add an address to a customer
      security:
        - OAuth:
            - customer
        - accessToken: []
  '/customers/{customerFid}/emails':
    post:
      summary: Add an email address to a customer
      security:
        - OAuth:
            - customer
        - accessToken: []
  '/customers/{customerFid}/phones':
    post:
      security:
        - OAuth:
            - customer
        - accessToken: []
      summary: Add a phone number to a customer
  '/customers/{customerFid}/invoices':
    get:
      summary: List of invoice summaries for given customer
      tags:
        - customers
      security:
        - OAuth:
            - customer
        - accessToken: []
  '/customers/{customerFid}/invoices/{invoiceFid}':
    get:
      summary: Retreive a specific itemised invoice
      tags:
        - customers
      security:
        - OAuth:
            - customer
        - accessToken: []
  '/customers/{customerFid}/invoices/retry':
    put:
      summary: Retry payment of all customer invoices which are in invoice
      tags:
        - customers
      security:
        - OAuth:
            - customer
        - accessToken: []
  '/customers/{customerFid}/invoices/{invoiceFid}/retry':
    put:
      summary: Retry payment of invoice
      tags:
        - customers
      security:
        - OAuth:
            - customer
        - accessToken: []
  '/customers/{customerFid}/invoices/{invoiceFid}/creditNote':
    post:
      security:
        - OAuth:
            - customer
        - accessToken: []
      summary: Add a credit note to a customers invoice
  '/customers/{customerFid}/subscriptions':
    get:
      summary: List of subscription summaries for given customer
      tags:
        - customers
      security:
        - OAuth:
            - customer
        - accessToken: []
  '/customers/{customerFid}/subscriptions/{subscriptionFid}':
    get:
      summary: Retreive a specific subscription
      tags:
        - customers
      security:
        - OAuth:
            - customer
        - accessToken: []
  '/customers/{customerFid}/subscriptions/{subscriptionFid}/enableAutoCharge':
    put:
      summary: Enable auto charge on specific subscription
      tags:
        - customers
      security:
        - OAuth:
            - customer
        - accessToken: []
  '/customers/{customerFid}/subscriptions/{subscriptionFid}/disableAutoCharge':
    put:
      summary: Disable auto charge on specific subscription
      tags:
        - customers
      security:
        - OAuth:
            - customer
        - accessToken: []
  '/customers/{customerFid}/subscriptions/{subscriptionFid}/autoCancelDays':
    put:
      summary: Set auto cancel days on a subscription
      tags:
        - customers
      security:
        - OAuth:
            - customer
        - accessToken: []
  '/customers/{customerFid}/subscriptions/{subscriptionFid}/autoSuspendDays':
    put:
      summary: Set auto suspend days on a subscription
      tags:
        - customers
      security:
        - OAuth:
            - customer
        - accessToken: []
  '/customers/{customerFid}/subscriptions/{subscriptionFid}/setAdvanceDays':
    put:
      summary: Set advance days on a subscription
      tags:
        - customers
      security:
        - OAuth:
            - customer
        - accessToken: []
  '/customers/{customerFid}/subscriptions/{subscriptionFid}/renewalMode':
    put:
      summary: Set the renewal mode of a subscription
      tags:
        - customers
      security:
        - OAuth:
            - customer
        - accessToken: []
  '/customers/{customerFid}/subscriptions/{subscriptionFid}/setParentSubscription':
    put:
      summary: Set parent subscription on a subscription
      tags:
        - customers
      security:
        - OAuth:
            - customer
        - accessToken: []
  '/customers/{customerFid}/subscriptions/{subscriptionFid}/calculateModification':
    put:
      summary: Calculates the changes before a modification to a subscription
      tags:
        - customers
      security:
        - OAuth:
            - customer
        - accessToken: []
  '/customers/{customerFid}/subscriptions/{subscriptionFid}/calculateRefund':
    put:
      summary: Calculates the result of a potential refund on a subscription
      tags:
        - customers
      security:
        - OAuth:
            - customer
        - accessToken: []
  '/customers/{customerFid}/subscriptions/{subscriptionFid}/setPaymentAccount':
    put:
      summary: Set paymentAccount for subscription. If changing a payment method from an Automatic Payment Method such as PayPal Recurring Payments, any other subscriptions paid with the same Agreement will be set to Default Payment Method and the Agreement will be cancelled
      tags:
        - customers
      security:
        - OAuth:
            - customer
        - accessToken: []
  '/customers/{customerFid}/subscriptions/{subscriptionFid}/modify':
    put:
      summary: Modify an existing subscription with a new price. Returns new open order to be completed
      tags:
        - customers
      security:
        - OAuth:
            - customer
        - accessToken: []
  '/customers/{customerFid}/subscriptions/{subscriptionFid}/updateRenewalPrice':
    put:
      summary: Modify an existing subscription with a new price which will be used for the next renewal
      tags:
        - customers
      security:
        - OAuth:
            - customer
        - accessToken: []
  '/customers/{customerFid}/subscriptions/{subscriptionFid}/applyOffer':
    put:
      summary: Apply an offer to a subscription
      tags:
        - customers
      security:
        - OAuth:
            - customer
        - accessToken: []
  '/customers/{customerFid}/subscriptions/{subscriptionFid}/preRenew':
    put:
      summary: Pre-renew an existing subscription with a different price. Returns new open order to be completed
      tags:
        - customers
      security:
        - OAuth:
            - customer
        - accessToken: []
  '/customers/{customerFid}/subscriptions/{subscriptionFid}/cancel':
    put:
      summary: Cancel a subscripion. Returns subscription FID.
      tags:
        - customers
      security:
        - OAuth:
            - customer
        - accessToken: []
  '/customers/{customerFid}/sar':
    post:
      summary: Subject Access Request
      tags:
        - customers
      description: |
        Initiate a Subject Access Request.  A URL will be sent via a webhook (CustomerWHE::SUBJECT_ACCESS_REQUEST), once the archive is ready for download
      security:
        - OAuth:
            - customer
        - accessToken: []
  '/customers/{customerFid}/anonymize':
    post:
      summary: Anonymize customer data
      tags:
        - customers
      description: |
        Anonymize customer data
      security:
        - OAuth:
            - customer
        - accessToken: []
  /products:
    get:
      summary: List all products
      tags:
        - products
      security:
        - OAuth:
            - product.readonly
        - accessToken: []
  '/products/{productFid}/prices':
    get:
      summary: Retrieve Product Prices
      tags:
        - products
      security:
        - OAuth:
            - product.readonly
        - accessToken: []
  '/products/groups':
    get:
      summary: Get a list of all product groups
      tags:
        - products
      security:
        - OAuth:
            - product.readonly
        - accessToken: []
  '/products/groups/{productGroupFid}/products':
    get:
      summary: Get a list of products belonging to the group
      tags:
        - products
      security:
        - OAuth:
            - product.readonly
        - accessToken: []
  /orders:
    post:
      summary: Create a new order
      tags:
        - orders
      security:
        - OAuth:
            - orders
        - accessToken: []
  '/orders/{orderFid}':
    get:
      summary: Retrieve an order
      tags:
        - orders
      security:
        - OAuth:
            - orders.readonly
        - accessToken: []
  '/orders/{orderFid}/verify':
    put:
      summary: Verify an order, returning any security urls
      tags:
        - orders
      security:
        - OAuth:
            - orders
        - accessToken: []
  '/orders/{orderFid}/cancel':
    put:
      summary: Cancel an order
      tags:
        - orders
      security:
        - OAuth:
            - orders
        - accessToken: []
  '/orders/{orderFid}/finalize':
    put:
      summary: Mark an order as finalized
      tags:
        - orders
      security:
        - OAuth:
            - orders
        - accessToken: []
  '/orders/{orderFid}/confirmCard':
    put:
      summary: Confirm an order, authorize the payment
      tags:
        - orders
      security:
        - OAuth:
            - orders
        - accessToken: []
  '/orders/{orderFid}/confirmPayPal':
    put:
      summary: Confirm an order, authorize the payment
      tags:
        - orders
      security:
        - OAuth:
            - orders
        - accessToken: []
  '/orders/{orderFid}/setChargeId':
    put:
      summary: Set a ChargeHive.com Charge ID on an order
      tags:
        - orders
      security:
        - OAuth:
            - orders
        - accessToken: []
  '/orders/{orderFid}/confirmNewCard':
    put:
      summary: Confirm an order with a new card, authorize the payment
      tags:
        - orders
      security:
        - OAuth:
            - orders
        - accessToken: []
  '/orders/{orderFid}/fraudScan':
    get:
      summary: Retrieve fraud scan
      tags:
        - orders
      security:
        - OAuth:
            - orders.readonly
        - accessToken: []
  '/orders/{orderFid}/products':
    get:
      summary: Retrieve order products
      tags:
        - orders
      security:
        - OAuth:
            - orders.readonly
        - accessToken: []
    post:
      summary: Add a product to an order
      tags:
        - orders
      security:
        - OAuth:
            - orders
        - accessToken: []
    put:
      summary: Set the products on an order
      tags:
        - orders
      security:
        - OAuth:
            - orders
        - accessToken: []
  '/orders/{orderFid}/products/{orderProductFid}':
    delete:
      summary: Remove a product from an order
      tags:
        - orders
      security:
        - OAuth:
            - orders
        - accessToken: []
  '/orders/{orderFid}/products/{orderProductFid}/quantity':
    put:
      summary: Set the quantity of a product on an order
      tags:
        - orders
      security:
        - OAuth:
            - orders
        - accessToken: []
  '/orders/{orderFid}/offers':
    post:
      summary: Add an offer to an order
      tags:
        - orders
      security:
        - OAuth:
            - orders
        - accessToken: []
  '/orders/{orderFid}/offers/{offerFid}':
    delete:
      summary: Remove an offer from an order
      tags:
        - orders
      security:
        - OAuth:
            - orders
        - accessToken: []
  '/messenger/deliveries/{deliveryFid}/unsubscribe':
    put:
      summary: Unsubscribe an email based on the delivery fid
      tags:
        - Contacts
        - Messenger
      security:
        - OAuth:
            - contact
        - accessToken: []
  '/messenger/deliveries/{deliveryFid}/subscribe':
    put:
      summary: Subscribe an email based on the delivery fid
      tags:
        - Contacts
        - Messenger
      security:
        - OAuth:
            - contact
        - accessToken: []
  '/contacts/emails/{emailAddress}/confirm':
    put:
      summary: Confirm email address
      tags:
        - Contacts
      security:
        - OAuth:
            - contact
        - accessToken: []
  '/contacts/emails/{emailAddress}/unsubscribe':
    put:
      summary: Unsubscribe an email address
      tags:
        - Contacts
      security:
        - OAuth:
            - contact
        - accessToken: []
  '/contacts/emails/{emailAddress}/subscribe':
    put:
      summary: Subscribe an email address
      tags:
        - Contacts
      security:
        - OAuth:
            - contact
        - accessToken: []
  '/polymers':
    post:
      summary: Create a new polymer
      tags:
        - polymers
      security:
        - OAuth:
            - polymer
        - accessToken: []
  '/polymers/{polymerFid}':
    get:
      summary: Read a polymer
      tags:
        - polymers
      security:
        - OAuth:
            - polymer.readonly
        - accessToken: []
  '/products/offers':
    get:
      summary: Retrieve all offers
      tags:
        - products
      security:
        - OAuth:
            - product.readonly
        - accessToken: []
  '/licence/check':
    get:
      summary: Retrieve A Licence
      tags:
        - licence
      security:
        - OAuth:
            - purchase.readonly
        - accessToken: []
  '/reasons/groups':
    get:
      summary: Get a list of all reason groups
      tags:
        - reasons
      security:
        - OAuth:
            - reasons.readonly
        - accessToken: []
  '/reasons/groups/{reasonGroupFid}':
    get:
      summary: Get all the reasons for the reason group
      tags:
        - reasons
      security:
        - OAuth:
            - reasons.readonly
        - accessToken: []
  '/tickets':
    post:
      summary: Create a support ticket
      tags:
        - support
      security:
        - OAuth:
            - support
        - accessToken: []
  '/services':
    get:
      summary: Retrieve all services
      tags:
        - ServiceStatus
      security:
        - OAuth:
            - entity.properties
        - accessToken: []
  '/services/{serviceFid}/incidents':
    get:
      summary: Retrieve incidents for service within timeframe
      tags:
        - ServiceStatus
      security:
        - OAuth:
            - entity.properties
        - accessToken: []
  '/services/{serviceFid}/incidents/{incidentFid}/updates':
    get:
      summary: Retrieve incident updates for incident
      tags:
        - ServiceStatus
      security:
        - OAuth:
            - entity.properties
        - accessToken: []
  '/configuration/finance/gateways':
    get:
      summary: Lists all the current gateways
      tags:
        - Configuration
      security:
        - OAuth:
            - configuration.readonly
        - accessToken: []
  '/integrations/verifyUser':
    get:
      summary: Verify a user
      security:
        - accessToken: []